//! Finding an `afni_proc.py` run and reading it from disk (the adapter).
//!
//! Only the directory you give is looked at: itself, its `proc.*` scripts,
//! its `<subj>.results` child named by the script, or, for a `*.results`
//! directory, the `proc.<subj>` script next to it. Parent trees are never
//! searched.

use std::collections::hash_map::DefaultHasher;
use std::fmt;
use std::hash::{Hash, Hasher};
use std::path::{Path, PathBuf};

use afni_io::brik::AfniPaths;
use afni_io::head::Header;

use super::health::{self, Facts};
use super::review::{Review, Warnings};
use super::script::{self, OutputKind, ParsedOutput, ParsedScript};
use super::{
    ArtifactRole, EvidenceSource, Health, HealthAssessment, ProcessingRun, ProcessingStep,
    SourceKind, Space, StepArtifact, StepId, StepKind,
};

/// Why a run could not be loaded.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DiscoverError {
    /// No `afni_proc.py` script in the place we are allowed to look.
    NoScript(PathBuf),
    /// The script could not be read.
    Unreadable(PathBuf, String),
    /// The file is not an `afni_proc.py`-generated script.
    NotAfniProc(PathBuf),
}

impl fmt::Display for DiscoverError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            DiscoverError::NoScript(d) => write!(
                f,
                "no afni_proc.py script (proc.<subject>) found in {}",
                d.display()
            ),
            DiscoverError::Unreadable(p, e) => write!(f, "cannot read {}: {e}", p.display()),
            DiscoverError::NotAfniProc(p) => {
                write!(f, "{} is not an afni_proc.py-generated script", p.display())
            }
        }
    }
}

impl std::error::Error for DiscoverError {}

/// Where a run's script and results are.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Located {
    /// The `proc.<subj>` script.
    pub script: PathBuf,
    /// The results directory (may not exist yet for a run that has not
    /// started).
    pub results: PathBuf,
}

/// Does this file start like an afni_proc.py script?
fn is_afni_proc_script(path: &Path) -> bool {
    std::fs::read_to_string(path)
        .map(|t| {
            t.lines()
                .take(8)
                .any(|l| l.contains("auto-generated by afni_proc.py"))
        })
        .unwrap_or(false)
}

/// Find the script and results for `dir` (see the module docs for the rules).
pub fn locate(dir: &Path) -> Result<Located, DiscoverError> {
    if !dir.is_dir() {
        return Err(DiscoverError::NoScript(dir.to_path_buf()));
    }
    // 1. A script in the directory itself.
    let mut scripts: Vec<PathBuf> = std::fs::read_dir(dir)
        .map(|rd| {
            rd.filter_map(Result::ok)
                .map(|e| e.path())
                .filter(|p| {
                    p.is_file()
                        && p.file_name()
                            .and_then(|n| n.to_str())
                            .is_some_and(|n| n.starts_with("proc.") && !n.ends_with(".log"))
                })
                .collect()
        })
        .unwrap_or_default();
    scripts.sort();
    if let Some(script) = scripts.into_iter().find(|p| is_afni_proc_script(p)) {
        let output_dir = std::fs::read_to_string(&script)
            .ok()
            .and_then(|t| script::parse(&t).ok())
            .and_then(|p| p.output_dir);
        let results = match output_dir {
            Some(od) => dir.join(od),
            None if dir.join("pb00.").exists() => dir.to_path_buf(),
            None => dir.to_path_buf(),
        };
        let results = if results.is_dir() || !dir.to_string_lossy().ends_with(".results") {
            results
        } else {
            dir.to_path_buf()
        };
        return Ok(Located { script, results });
    }
    // 2. A `<subj>.results` directory: the script sits next to it.
    if let Some(stem) = dir
        .file_name()
        .and_then(|n| n.to_str())
        .and_then(|n| n.strip_suffix(".results"))
        && let Some(parent) = dir.parent()
    {
        let script = parent.join(format!("proc.{stem}"));
        if is_afni_proc_script(&script) {
            return Ok(Located {
                script,
                results: dir.to_path_buf(),
            });
        }
    }
    Err(DiscoverError::NoScript(dir.to_path_buf()))
}

/// Find and load the run in `dir`.
#[cfg(test)]
pub fn load_run(dir: &Path) -> Result<ProcessingRun, DiscoverError> {
    let at = locate(dir)?;
    load_located(&at)
}

/// Load a located run.
pub fn load_located(at: &Located) -> Result<ProcessingRun, DiscoverError> {
    let text = std::fs::read_to_string(&at.script)
        .map_err(|e| DiscoverError::Unreadable(at.script.clone(), e.to_string()))?;
    let parsed = script::parse(&text).map_err(|_| DiscoverError::NotAfniProc(at.script.clone()))?;
    Ok(build_run(at, &parsed))
}

/// Combine a parsed script with what is on disk.
fn build_run(at: &Located, parsed: &ParsedScript) -> ProcessingRun {
    let script_name = at.script.file_name().map_or_else(
        || "script".to_string(),
        |n| n.to_string_lossy().into_owned(),
    );
    let mut steps: Vec<ProcessingStep> = Vec::new();
    for ps in &parsed.steps {
        let seen = steps.iter().filter(|s| s.block == ps.block).count();
        let kind = StepKind::from_block(&ps.block);
        let (id, label) = if seen == 0 {
            (ps.block.clone(), kind.label())
        } else {
            (
                format!("{}#{}", ps.block, seen + 1),
                format!("{} ({})", kind.label(), seen + 1),
            )
        };
        let artifacts = ps
            .outputs
            .iter()
            .map(|o| {
                // A name written by an earlier step again (anat_ns: first in
                // the subject's space, then in the template's) is the later
                // view: prefer it.
                let again = steps
                    .iter()
                    .any(|s| s.artifacts.iter().any(|a| a.name == o.name));
                artifact(&at.results, o, &script_name, again)
            })
            .collect();
        steps.push(ProcessingStep {
            id: StepId(id),
            kind,
            label,
            block: ps.block.clone(),
            script_line: ps.line,
            artifacts,
            assessment: HealthAssessment {
                health: Health::Unknown,
                evidence: vec![],
            },
        });
    }
    let facts = load_facts(&at.results, parsed.subject.as_deref());
    health::assess(&mut steps, &facts);

    let mut notes = parsed.notes.clone();
    if !at.results.is_dir() {
        notes.push(format!(
            "results directory {} does not exist yet",
            at.results.display()
        ));
    }
    ProcessingRun {
        tool: "afni_proc.py".to_string(),
        name: parsed
            .subject
            .clone()
            .unwrap_or_else(|| script_name.trim_start_matches("proc.").to_string()),
        script: at.script.clone(),
        results_dir: at.results.clone(),
        command: parsed.command.clone(),
        steps,
        notes,
    }
}

/// The AFNI views, as file name suffixes.
const VIEWS: [&str; 3] = ["+orig", "+acpc", "+tlrc"];

/// Files a dataset named `name` may be stored as, most likely first.
pub fn candidate_paths(results: &Path, name: &str, is_dataset: bool) -> Vec<PathBuf> {
    if !is_dataset {
        return vec![results.join(name)];
    }
    if VIEWS.iter().any(|v| name.ends_with(v)) {
        return vec![results.join(format!("{name}.HEAD"))];
    }
    if name.ends_with(".nii") || name.ends_with(".nii.gz") {
        return vec![results.join(name)];
    }
    let mut out: Vec<PathBuf> = VIEWS
        .iter()
        .map(|v| results.join(format!("{name}{v}.HEAD")))
        .collect();
    out.push(results.join(format!("{name}.nii")));
    out.push(results.join(format!("{name}.nii.gz")));
    out
}

/// Extensions that mark a file that is not a volume dataset.
const FILE_EXTENSIONS: [&str; 6] = [".1D", ".txt", ".json", ".csv", ".jpg", ".html"];

fn artifact(
    results: &Path,
    out: &ParsedOutput,
    script: &str,
    prefer_later_view: bool,
) -> StepArtifact {
    let is_dataset =
        out.kind == OutputKind::Dataset && !FILE_EXTENSIONS.iter().any(|e| out.name.ends_with(e));
    let mut candidates = candidate_paths(results, &out.name, is_dataset);
    if prefer_later_view {
        candidates.reverse();
    }
    let found = candidates.iter().find(|p| p.is_file());
    let path = found.cloned().unwrap_or_else(|| results.join(&out.name));
    let space = space_of(
        found.map_or(out.name.as_str(), |p| p.to_str().unwrap_or("")),
        &out.name,
    );
    let (openable, open_error, dims) = match found {
        Some(p) if is_dataset && p.to_string_lossy().ends_with(".HEAD") => check_afni(p),
        _ => (None, None, None),
    };
    StepArtifact {
        name: out.name.clone(),
        role: classify(&out.name),
        space,
        is_dataset,
        exists: found.is_some(),
        path,
        openable,
        open_error,
        dims,
        source: EvidenceSource {
            kind: SourceKind::GeneratedCommand,
            detail: format!("{script}:{}", out.line),
        },
    }
}

fn space_of(resolved: &str, name: &str) -> Space {
    for text in [resolved, name] {
        let text = text.trim_end_matches(".HEAD");
        if text.ends_with("+orig") {
            return Space::Orig;
        }
        if text.ends_with("+acpc") {
            return Space::Acpc;
        }
        if text.ends_with("+tlrc") {
            return Space::Tlrc;
        }
    }
    Space::Unknown
}

/// Open an AFNI dataset's header (not its voxels): can `afni-io` read it?
fn check_afni(head: &Path) -> (Option<bool>, Option<String>, Option<[usize; 3]>) {
    let result = (|| -> Result<[usize; 3], String> {
        let paths = AfniPaths::resolve(head).map_err(|e| e.to_string())?;
        if paths.brik.is_none() {
            return Err("no BRIK file".to_string());
        }
        let text = std::fs::read_to_string(&paths.head).map_err(|e| e.to_string())?;
        let header = Header::parse(&text).map_err(|e| e.to_string())?;
        header
            .dimensions()
            .ok_or_else(|| "no DATASET_DIMENSIONS".to_string())
    })();
    match result {
        Ok(dims) => (Some(true), None, Some(dims)),
        Err(e) => (Some(false), Some(e), None),
    }
}

/// Guess what a file is for from its name (afni_proc.py's naming).
pub fn classify(name: &str) -> ArtifactRole {
    let n = name;
    let has = |s: &str| n.contains(s);
    if n.starts_with("out.") || n.ends_with(".txt") || n.ends_with(".json") {
        ArtifactRole::Report
    } else if has("mask") {
        ArtifactRole::Mask
    } else if n.starts_with("stats") {
        ArtifactRole::Stats
    } else if n.starts_with("errts") || n.starts_with("fitts") {
        ArtifactRole::Residual
    } else if has("xmat") || has("ideal") || has("regressors") {
        ArtifactRole::Regressors
    } else if has("censor") || n.starts_with("outcount") {
        ArtifactRole::Censor
    } else if has("dfile") || has("motion") {
        ArtifactRole::Motion
    } else if has("mat.") || has("aff12") || has("WARP") || has("Xat") {
        ArtifactRole::Transform
    } else if n.starts_with("anat") || has("anat_") {
        ArtifactRole::Anat
    } else if n.starts_with("pb")
        || has("epi")
        || n.starts_with("all_runs")
        || n.starts_with("vr_base")
    {
        ArtifactRole::Epi
    } else {
        ArtifactRole::Other
    }
}

/// Read the QC files the health rules use.
pub fn load_facts(results: &Path, subject: Option<&str>) -> Facts {
    let read = |name: &str| std::fs::read_to_string(results.join(name)).ok();
    let warnings = |name: &str| read(name).map(|t| Warnings::parse(name, &t));
    let review_name = subject
        .map(|s| format!("out.ss_review.{s}.txt"))
        .filter(|n| results.join(n).is_file())
        .or_else(|| {
            // One review file under another subject name is still the review.
            let mut found: Vec<String> = std::fs::read_dir(results)
                .ok()?
                .filter_map(Result::ok)
                .filter_map(|e| e.file_name().into_string().ok())
                .filter(|n| n.starts_with("out.ss_review.") && n.ends_with(".txt"))
                .collect();
            found.sort();
            (found.len() == 1).then(|| found.remove(0))
        });
    Facts {
        review: review_name.and_then(|n| read(&n).map(|t| Review::parse(&n, &t))),
        pre_ss_warn: warnings("out.pre_ss_warn.txt"),
        warn_4095: warnings("out.4095_warn.txt"),
        cormat_warn: warnings("out.cormat_warn.txt"),
    }
}

/// A number that changes whenever a file the run depends on appears,
/// disappears or changes (its size or modification time). Cheap: it looks
/// only at the paths the run already knows.
pub fn fingerprint(run: &ProcessingRun) -> u64 {
    let mut h = DefaultHasher::new();
    let stat = |h: &mut DefaultHasher, p: &Path| match std::fs::metadata(p) {
        Ok(m) => {
            1u8.hash(h);
            m.len().hash(h);
            m.modified()
                .ok()
                .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
                .map(|d| d.as_nanos())
                .hash(h);
        }
        Err(_) => 0u8.hash(h),
    };
    stat(&mut h, &run.script);
    for step in &run.steps {
        for a in &step.artifacts {
            for p in candidate_paths(&run.results_dir, &a.name, a.is_dataset) {
                stat(&mut h, &p);
            }
        }
    }
    for name in [
        "out.pre_ss_warn.txt",
        "out.4095_warn.txt",
        "out.cormat_warn.txt",
    ] {
        stat(&mut h, &run.results_dir.join(name));
    }
    if let Ok(rd) = std::fs::read_dir(&run.results_dir) {
        let mut reviews: Vec<PathBuf> = rd
            .filter_map(Result::ok)
            .map(|e| e.path())
            .filter(|p| {
                p.file_name()
                    .and_then(|n| n.to_str())
                    .is_some_and(|n| n.starts_with("out.ss_review."))
            })
            .collect();
        reviews.sort();
        for p in reviews {
            stat(&mut h, &p);
        }
    }
    h.finish()
}

#[cfg(test)]
pub(crate) mod testkit {
    //! Builds results directories for the committed scripts: a tiny dataset
    //! or file for every output the script declares (except those skipped).

    use std::fs;
    use std::path::{Path, PathBuf};

    use afni_io::brik::{BrickData, Brik, SubBrick};
    use afni_io::geometry::Orientation;

    use crate::processing::script::{self, OutputKind};
    use crate::testutil::TempDir;

    pub const GOOD_REVIEW: &str = "\
subject ID                : sub-01
TR                        : 2
motion limit              : 0.3
censor fraction           : 0.033333
degrees of freedom left   : 270
anat/EPI mask Dice coef   : 0.94
anat/templ mask Dice coef : 0.97
";

    pub fn script_text(case: &str) -> String {
        let p = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/processing")
            .join(case)
            .join("proc.sub-01");
        fs::read_to_string(p).unwrap()
    }

    /// Write a tiny AFNI dataset `name` (with view) of the given size.
    pub fn write_dataset(path_with_view: &Path, dims: [usize; 3]) {
        let n = dims[0] * dims[1] * dims[2];
        let sub = SubBrick {
            data: BrickData::Float(vec![1.0; n]),
            factor: 0.0,
        };
        let brik = Brik::new(
            dims,
            [Orientation::R2L, Orientation::A2P, Orientation::I2S],
            [0.0; 3],
            [1.0; 3],
            vec![sub],
        )
        .unwrap();
        brik.write(path_with_view).unwrap();
    }

    /// A temp dir holding `proc.sub-01` of `case` and results for it.
    /// `skip` lists output names to leave out; `limit` stops after that many
    /// steps (an unfinished run).
    pub fn build(case: &str, skip: &[&str], limit: Option<usize>) -> (TempDir, PathBuf) {
        let tmp = TempDir::new(case);
        let text = script_text(case);
        fs::write(tmp.path().join("proc.sub-01"), &text).unwrap();
        let results = tmp.path().join("sub-01.results");
        fs::create_dir_all(&results).unwrap();
        let parsed = script::parse(&text).unwrap();
        // Outputs are in the subject's space until the template warp, then in
        // the template's (the same name can exist in both views).
        let tlrc_at = parsed.steps.iter().position(|s| s.block == "tlrc");
        for (n, step) in parsed
            .steps
            .iter()
            .take(limit.unwrap_or(usize::MAX))
            .enumerate()
        {
            let view = if tlrc_at.is_some_and(|t| n >= t) {
                "+tlrc"
            } else {
                "+orig"
            };
            for o in &step.outputs {
                if skip.contains(&o.name.as_str()) {
                    continue;
                }
                let is_file = o.kind == OutputKind::File
                    || o.name.contains(".1D")
                    || o.name.ends_with(".txt");
                if is_file {
                    fs::write(results.join(&o.name), "0\n").unwrap();
                } else {
                    let named = if ["+orig", "+tlrc", "+acpc"]
                        .iter()
                        .any(|v| o.name.ends_with(v))
                    {
                        o.name.clone()
                    } else {
                        format!("{}{view}", o.name)
                    };
                    write_dataset(&results.join(named), [4, 5, 6]);
                }
            }
        }
        fs::write(results.join("out.ss_review.sub-01.txt"), GOOD_REVIEW).unwrap();
        for w in [
            "out.pre_ss_warn.txt",
            "out.4095_warn.txt",
            "out.cormat_warn.txt",
        ] {
            fs::write(results.join(w), "").unwrap();
        }
        (tmp, results)
    }
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::testkit::*;
    use super::*;
    use crate::testutil::TempDir;

    fn step<'a>(run: &'a ProcessingRun, block: &str) -> &'a ProcessingStep {
        run.steps.iter().find(|s| s.block == block).unwrap()
    }

    #[test]
    fn a_complete_run_loads_with_steps_in_order_and_all_artifacts() {
        let (tmp, _) = build("complete", &[], None);
        let run = load_run(tmp.path()).unwrap();
        assert_eq!(run.name, "sub-01");
        assert_eq!(run.tool, "afni_proc.py");
        let labels: Vec<_> = run.steps.iter().map(|s| s.label.as_str()).collect();
        assert_eq!(
            labels,
            [
                "Inputs",
                "Outlier check",
                "Slice timing",
                "Alignment",
                "Template warp",
                "Motion correction",
                "Smoothing",
                "Masks",
                "Scaling",
                "Regression"
            ]
        );
        assert!(
            run.command
                .as_deref()
                .unwrap()
                .starts_with("afni_proc.py -subj_id sub-01")
        );
        for s in &run.steps {
            for a in &s.artifacts {
                assert!(a.exists, "{} missing", a.name);
            }
        }
    }

    #[test]
    fn artifacts_get_roles_spaces_and_header_facts() {
        let (tmp, results) = build("complete", &[], None);
        let run = load_run(tmp.path()).unwrap();
        let tshift = &step(&run, "tshift").artifacts[0];
        assert_eq!(tshift.name, "pb01.sub-01.r01.tshift");
        assert_eq!(tshift.role, ArtifactRole::Epi);
        assert_eq!(tshift.space, Space::Orig);
        assert!(tshift.exists && tshift.is_dataset);
        assert_eq!(tshift.openable, Some(true));
        assert_eq!(tshift.dims, Some([4, 5, 6]));
        assert_eq!(
            tshift.path,
            results.join("pb01.sub-01.r01.tshift+orig.HEAD")
        );
        assert!(
            tshift.source.detail.starts_with("proc.sub-01:"),
            "{}",
            tshift.source.detail
        );
        let blur = &step(&run, "blur").artifacts[0];
        assert_eq!(blur.space, Space::Tlrc);
        let stats = step(&run, "regress")
            .artifacts
            .iter()
            .find(|a| a.name == "stats.sub-01")
            .unwrap();
        assert_eq!(stats.role, ArtifactRole::Stats);
        let mask = step(&run, "mask")
            .artifacts
            .iter()
            .find(|a| a.name == "full_mask.sub-01")
            .unwrap();
        assert_eq!(mask.role, ArtifactRole::Mask);
    }

    #[test]
    fn a_name_written_twice_resolves_to_the_later_view_in_the_later_step() {
        let (tmp, _) = build("complete", &[], None);
        let run = load_run(tmp.path()).unwrap();
        let ns = |block: &str| {
            step(&run, block)
                .artifacts
                .iter()
                .find(|a| a.name == "anat_ns")
                .unwrap()
        };
        assert_eq!(ns("align").space, Space::Orig);
        assert_eq!(ns("tlrc").space, Space::Tlrc);
        assert_ne!(ns("align").path, ns("tlrc").path);
        // Alignment now has datasets of its own to view.
        assert_eq!(step(&run, "align").viewable().len(), 2);
    }

    #[test]
    fn a_complete_run_with_good_review_is_good_where_measured() {
        let (tmp, _) = build("complete", &[], None);
        let run = load_run(tmp.path()).unwrap();
        for block in [
            "tcat", "tshift", "tlrc", "volreg", "blur", "scale", "regress",
        ] {
            let s = step(&run, block);
            assert!(
                matches!(s.assessment.health, Health::Good),
                "{block}: {:?} {}",
                s.assessment.health,
                s.assessment.reason()
            );
        }
    }

    #[test]
    fn missing_output_before_later_outputs_fails_that_step_only() {
        let (tmp, _) = build("complete", &["pb03.sub-01.r01.blur"], None);
        let run = load_run(tmp.path()).unwrap();
        assert_eq!(step(&run, "blur").assessment.health, Health::Failed);
        assert_eq!(step(&run, "tshift").assessment.health, Health::Good);
        assert!(
            !step(&run, "blur")
                .viewable()
                .iter()
                .any(|a| a.name.contains("pb03"))
        );
    }

    #[test]
    fn an_unfinished_run_is_unknown_beyond_where_it_got() {
        let (tmp, _) = build("complete", &[], Some(3)); // tcat, outcount, tshift
        let run = load_run(tmp.path()).unwrap();
        assert_eq!(step(&run, "tshift").assessment.health, Health::Good);
        for block in ["volreg", "blur", "scale", "regress"] {
            assert_eq!(
                step(&run, block).assessment.health,
                Health::Unknown,
                "{block}"
            );
        }
    }

    #[test]
    fn two_runs_produce_one_artifact_per_run() {
        let (tmp, _) = build("two_runs", &[], None);
        let run = load_run(tmp.path()).unwrap();
        let t = &step(&run, "tshift").artifacts;
        assert_eq!(t.iter().filter(|a| a.name.starts_with("pb01")).count(), 2);
        assert!(
            step(&run, "tshift")
                .assessment
                .evidence
                .iter()
                .any(|e| e.check == "grid.runs")
        );
    }

    #[test]
    fn mismatched_run_grids_fail_the_step() {
        let (tmp, results) = build("two_runs", &[], None);
        write_dataset(&results.join("pb01.sub-01.r02.tshift+orig"), [4, 5, 7]);
        let run = load_run(tmp.path()).unwrap();
        assert_eq!(step(&run, "tshift").assessment.health, Health::Failed);
    }

    #[test]
    fn a_corrupt_header_is_reported_as_unopenable() {
        let (tmp, results) = build("complete", &[], None);
        fs::write(results.join("pb01.sub-01.r01.tshift+orig.HEAD"), "garbage").unwrap();
        let run = load_run(tmp.path()).unwrap();
        let a = &step(&run, "tshift").artifacts[0];
        assert_eq!(a.openable, Some(false));
        assert!(a.open_error.is_some());
        assert_eq!(step(&run, "tshift").assessment.health, Health::Failed);
        assert!(
            !step(&run, "tshift")
                .viewable()
                .iter()
                .any(|a| a.name.starts_with("pb01"))
        );
    }

    #[test]
    fn omitted_and_custom_order_runs_load() {
        let (tmp, _) = build("omitted", &[], None);
        let run = load_run(tmp.path()).unwrap();
        assert_eq!(run.steps.len(), 5);
        let (tmp, _) = build("custom_order", &[], None);
        let run = load_run(tmp.path()).unwrap();
        let blocks: Vec<_> = run.steps.iter().map(|s| s.block.as_str()).collect();
        assert_eq!(
            blocks,
            ["tcat", "outcount", "tshift", "blur", "volreg", "regress"]
        );
    }

    #[test]
    fn a_not_yet_created_results_dir_gives_an_unknown_run() {
        let tmp = TempDir::new("noresults");
        fs::write(tmp.path().join("proc.sub-01"), script_text("complete")).unwrap();
        let run = load_run(tmp.path()).unwrap();
        assert!(run.notes.iter().any(|n| n.contains("does not exist yet")));
        assert!(
            run.steps
                .iter()
                .all(|s| s.assessment.health == Health::Unknown)
        );
    }

    #[test]
    fn locate_works_from_the_results_directory_and_from_its_parent() {
        let (tmp, results) = build("complete", &[], None);
        let from_parent = locate(tmp.path()).unwrap();
        assert_eq!(from_parent.script, tmp.path().join("proc.sub-01"));
        assert_eq!(from_parent.results, tmp.path().join("sub-01.results"));
        let from_results = locate(&results).unwrap();
        assert_eq!(from_results, from_parent);
    }

    #[test]
    fn locate_does_not_search_unrelated_trees() {
        let tmp = TempDir::new("unrelated");
        fs::create_dir_all(tmp.path().join("deep/er")).unwrap();
        fs::write(
            tmp.path().join("deep/er/proc.sub-01"),
            script_text("complete"),
        )
        .unwrap();
        // The script is two levels down: not found from here.
        assert!(matches!(
            locate(tmp.path()),
            Err(DiscoverError::NoScript(_))
        ));
        // A directory that is not *.results does not look at its parent.
        let sibling = tmp.path().join("other");
        fs::create_dir_all(&sibling).unwrap();
        fs::write(tmp.path().join("proc.other"), script_text("complete")).unwrap();
        assert!(matches!(locate(&sibling), Err(DiscoverError::NoScript(_))));
    }

    #[test]
    fn a_proc_file_that_is_not_from_afni_proc_is_not_a_script() {
        let tmp = TempDir::new("fake");
        fs::write(tmp.path().join("proc.foo"), "#!/bin/tcsh\necho hi\n").unwrap();
        assert!(matches!(
            locate(tmp.path()),
            Err(DiscoverError::NoScript(_))
        ));
        assert!(matches!(
            load_run(&tmp.path().join("missing")),
            Err(DiscoverError::NoScript(_))
        ));
    }

    #[test]
    fn a_truncated_script_loads_what_it_has() {
        let tmp = TempDir::new("trunc");
        let head: String = script_text("complete")
            .lines()
            .take(100)
            .collect::<Vec<_>>()
            .join("\n");
        fs::write(tmp.path().join("proc.sub-01"), head).unwrap();
        let run = load_run(tmp.path()).unwrap();
        assert_eq!(run.steps.len(), 2);
    }

    #[test]
    fn the_fingerprint_changes_when_outputs_appear() {
        let (tmp, results) = build("complete", &[], Some(3));
        let run = load_run(tmp.path()).unwrap();
        let before = fingerprint(&run);
        assert_eq!(before, fingerprint(&run));
        write_dataset(&results.join("pb02.sub-01.r01.volreg+tlrc"), [4, 5, 6]);
        assert_ne!(before, fingerprint(&run));
    }

    #[test]
    fn reviews_under_another_subject_name_are_still_found() {
        let tmp = TempDir::new("review");
        fs::write(tmp.path().join("out.ss_review.other.txt"), GOOD_REVIEW).unwrap();
        let f = load_facts(tmp.path(), Some("sub-01"));
        assert_eq!(f.review.unwrap().file, "out.ss_review.other.txt");
        assert!(f.pre_ss_warn.is_none());
    }

    #[test]
    fn classify_covers_afni_proc_names() {
        use ArtifactRole::*;
        for (name, role) in [
            ("pb02.sub-01.r01.volreg", Epi),
            ("anat_final.sub-01", Anat),
            ("mask_anat.sub-01", Mask),
            ("full_mask.sub-01", Mask),
            ("stats.sub-01", Stats),
            ("errts.sub-01", Residual),
            ("X.xmat.1D", Regressors),
            ("censor_sub-01_combined_2.1D", Censor),
            ("outcount_rall.1D", Censor),
            ("dfile_rall.1D", Motion),
            ("mat.r01.warp.aff12.1D", Transform),
            ("out.mask_ae_dice.txt", Report),
            ("final_epi_vr_base_min_outlier", Epi),
        ] {
            assert_eq!(classify(name), role, "{name}");
        }
    }
}
