//! Parsing an `afni_proc.py`-generated `proc.<subj>` script (the adapter).
//!
//! The script is a tcsh file. afniru does not run or fully understand it; it
//! reads exactly what is stable and visible:
//!
//! * the **banners** `# ====== name ======` (and `# ===== auto block: name
//!   =====`), whose order is the executed order,
//! * within each block, the **outputs** named by common options (`-prefix`,
//!   `-bucket`, `-x1D`, `-errts`, `-write*`, ...), `3dcopy` destinations,
//!   and `> file` / `| tee file` redirects,
//! * `set subj`, `set output_dir`, the run list from `count_afni`, and the
//!   `afni_proc.py` command recorded in the trailing comment.
//!
//! Everything is attributed to a script line number.

use std::fmt;

/// Why a script could not be used.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ScriptError {
    /// The text is not an `afni_proc.py`-generated script.
    NotAfniProc,
}

impl fmt::Display for ScriptError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ScriptError::NotAfniProc => write!(f, "not an afni_proc.py-generated script"),
        }
    }
}

impl std::error::Error for ScriptError {}

/// How an output was named.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OutputKind {
    /// `-prefix`, `-bucket`, `-errts`, ... of an AFNI program, or `3dcopy`:
    /// normally a volume dataset.
    Dataset,
    /// A redirect, `tee`, `-x1D` or `-write*`: a file.
    File,
}

/// One output a block writes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParsedOutput {
    /// Name with variables filled in, e.g. `pb01.sub-01.r01.tshift`.
    pub name: String,
    /// Script line (1-based) of the command.
    pub line: usize,
    /// Dataset or file.
    pub kind: OutputKind,
}

/// One block of the script.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParsedStep {
    /// Block name, e.g. `volreg`.
    pub block: String,
    /// Banner said `auto block:`.
    pub auto: bool,
    /// Line of the banner (1-based).
    pub line: usize,
    /// Outputs in script order, without duplicates.
    pub outputs: Vec<ParsedOutput>,
}

/// What was read from a script.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParsedScript {
    /// `set subj = ...`.
    pub subject: Option<String>,
    /// `set output_dir = ...`.
    pub output_dir: Option<String>,
    /// Run labels from `count_afni -digits D 1 N` (`01`, `02`, ...), or `01`.
    pub runs: Vec<String>,
    /// The generating command, from the trailing comment.
    pub command: Option<String>,
    /// Blocks in executed order.
    pub steps: Vec<ParsedStep>,
    /// Things that looked odd but did not stop the parse.
    pub notes: Vec<String>,
}

/// Banners that are not data-processing steps.
const IGNORED_BLOCKS: [&str; 4] = ["setup", "finalize", "QC_review", "blur estimation"];

/// Options whose next token is an output dataset.
const DATASET_OPTIONS: [&str; 8] = [
    "-prefix", "-bucket", "-cbucket", "-errts", "-fitts", "-Rbuck", "-Rerrts", "-Rfitts",
];

/// Parse a script.
pub fn parse(text: &str) -> Result<ParsedScript, ScriptError> {
    let lines: Vec<&str> = text.lines().collect();
    if !lines
        .iter()
        .take(8)
        .any(|l| l.contains("auto-generated by afni_proc.py"))
    {
        return Err(ScriptError::NotAfniProc);
    }

    let subject = set_value(&lines, "subj");
    let output_dir = set_value(&lines, "output_dir");
    let runs = run_labels(&lines);
    let command = recorded_command(&lines);
    let mut notes = Vec::new();

    let mut steps: Vec<ParsedStep> = Vec::new();
    let mut current: Option<usize> = None;
    let mut i = 0;
    while i < lines.len() {
        let raw = lines[i];
        if let Some((block, auto)) = banner(raw) {
            if IGNORED_BLOCKS.contains(&block.as_str()) {
                current = None;
            } else {
                steps.push(ParsedStep {
                    block,
                    auto,
                    line: i + 1,
                    outputs: Vec::new(),
                });
                current = Some(steps.len() - 1);
            }
            i += 1;
            continue;
        }
        // A command may continue over lines ending in a backslash.
        let start = i;
        let mut logical = raw.trim().to_string();
        while logical.ends_with('\\') && i + 1 < lines.len() {
            logical.pop();
            i += 1;
            logical.push(' ');
            logical.push_str(lines[i].trim());
        }
        i += 1;
        let Some(step) = current else { continue };
        if logical.starts_with('#') || logical.is_empty() {
            continue;
        }
        for (name, kind) in outputs_of(&logical) {
            for name in expand(&name, subject.as_deref(), &runs) {
                if keep(&name) && !steps[step].outputs.iter().any(|o| o.name == name) {
                    steps[step].outputs.push(ParsedOutput {
                        name,
                        line: start + 1,
                        kind,
                    });
                }
            }
        }
    }
    if steps.is_empty() {
        notes.push("no processing blocks (# ==== name ==== banners) found".to_string());
    }
    Ok(ParsedScript {
        subject,
        output_dir,
        runs,
        command,
        steps,
        notes,
    })
}

/// `# ===== name =====` → (`name`, false); `# ===== auto block: name =====`
/// → (`name`, true). Lines of only `=` are not banners.
fn banner(line: &str) -> Option<(String, bool)> {
    let t = line.trim();
    let inner = t.strip_prefix('#')?.trim();
    if !(inner.starts_with("==") && inner.ends_with("==")) {
        return None;
    }
    let name = inner.trim_matches('=').trim();
    if name.is_empty() {
        return None;
    }
    match name.strip_prefix("auto block:") {
        Some(rest) => Some((rest.trim().to_string(), true)),
        None => Some((name.to_string(), false)),
    }
}

/// The value of the first `set <var> = value` that is a plain word.
fn set_value(lines: &[&str], var: &str) -> Option<String> {
    lines.iter().find_map(|l| {
        let rest = l
            .trim()
            .strip_prefix("set ")?
            .trim_start()
            .strip_prefix(var)?;
        let value = rest.trim_start().strip_prefix('=')?.trim();
        // `set subj = $argv[1]` comes first in the script; the default that
        // follows it in the `else` branch is the real name.
        (!value.is_empty() && !value.starts_with('(') && !value.contains('$'))
            .then(|| value.to_string())
    })
}

/// Run labels from `count_afni -digits D 1 N`; `["01"]` when absent.
fn run_labels(lines: &[&str]) -> Vec<String> {
    for l in lines {
        if let Some(rest) = l.split("count_afni").nth(1) {
            let tokens: Vec<&str> = rest
                .trim_end_matches(['`', ')', ' '])
                .split_whitespace()
                .collect();
            if let Some(d) = tokens.iter().position(|t| *t == "-digits")
                && let (Some(width), Some(n)) = (
                    tokens.get(d + 1).and_then(|t| t.parse::<usize>().ok()),
                    tokens.last().and_then(|t| t.parse::<usize>().ok()),
                )
            {
                return (1..=n).map(|r| format!("{r:0width$}")).collect();
            }
        }
    }
    vec!["01".to_string()]
}

/// The `afni_proc.py ...` command from the comment block after
/// `# script generated by the command:`.
fn recorded_command(lines: &[&str]) -> Option<String> {
    let start = lines
        .iter()
        .position(|l| l.contains("script generated by the command"))?;
    let mut parts = Vec::new();
    for l in &lines[start + 1..] {
        let Some(body) = l.trim().strip_prefix('#') else {
            break;
        };
        let body = body.trim();
        if body.is_empty() {
            continue;
        }
        parts.push(body.trim_end_matches('\\').trim().to_string());
    }
    (!parts.is_empty()).then(|| parts.join(" "))
}

/// Split a command line into tokens, keeping quoted parts attached.
fn tokens(line: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut cur = String::new();
    let mut quote: Option<char> = None;
    for c in line.chars() {
        match (quote, c) {
            (Some(q), c) if c == q => quote = None,
            (Some(_), c) => cur.push(c),
            (None, '\'' | '"') => quote = Some(c),
            (None, c) if c.is_whitespace() => {
                if !cur.is_empty() {
                    out.push(std::mem::take(&mut cur));
                }
            }
            (None, c) => cur.push(c),
        }
    }
    if !cur.is_empty() {
        out.push(cur);
    }
    out
}

/// Output names a command line mentions (variables not yet expanded).
fn outputs_of(line: &str) -> Vec<(String, OutputKind)> {
    let toks = tokens(line);
    let mut out = Vec::new();
    for (n, t) in toks.iter().enumerate() {
        let next = toks.get(n + 1);
        if DATASET_OPTIONS.contains(&t.as_str()) {
            if let Some(v) = next {
                out.push((v.clone(), OutputKind::Dataset));
            }
        } else if t == "-x1D"
            || t == "-xjpeg"
            || t.starts_with("-write") && t != "-write_uvars_json"
            || matches!(t.as_str(), ">" | ">>" | ">&" | ">>&")
        {
            if let Some(v) = next {
                out.push((v.clone(), OutputKind::File));
            }
        } else if t == "tee" {
            // `tee [-a] file`
            if let Some(v) = toks[n + 1..].iter().find(|v| !v.starts_with('-')) {
                out.push((v.clone(), OutputKind::File));
            }
        }
    }
    if toks.first().map(String::as_str) == Some("align_epi_anat.py") {
        out.extend(align_epi_anat_outputs(&toks));
    }
    if toks.first().map(String::as_str) == Some("3dcopy")
        && toks.len() >= 3
        && let Some(dest) = toks.last()
    {
        out.push((dest.clone(), OutputKind::Dataset));
    }
    out
}

/// `align_epi_anat.py` names its outputs from `-anat` and `-suffix` instead of
/// `-prefix`: the aligned anatomy `<anat><suffix>` (default suffix `_al`), its
/// matrix `<anat><suffix>_mat.aff12.1D`, and with `-save_skullstrip` the
/// skull-stripped anatomy `<anat>_ns`.
fn align_epi_anat_outputs(toks: &[String]) -> Vec<(String, OutputKind)> {
    let value = |opt: &str| {
        toks.iter()
            .position(|t| t == opt)
            .and_then(|i| toks.get(i + 1))
    };
    let Some(anat) = value("-anat") else {
        return Vec::new();
    };
    let base = ["+orig", "+acpc", "+tlrc"]
        .iter()
        .find_map(|v| anat.split(v).next().filter(|_| anat.contains(v)))
        .unwrap_or(anat)
        .trim_end_matches(".HEAD");
    let suffix = value("-suffix").map_or("_al", String::as_str);
    let mut out = vec![
        (format!("{base}{suffix}"), OutputKind::Dataset),
        (format!("{base}{suffix}_mat.aff12.1D"), OutputKind::File),
    ];
    if toks.iter().any(|t| t == "-save_skullstrip") {
        out.push((format!("{base}_ns"), OutputKind::Dataset));
    }
    out
}

/// Fill in `$subj` and `$run`; one name per run when `$run` appears.
fn expand(name: &str, subject: Option<&str>, runs: &[String]) -> Vec<String> {
    let mut n = name
        .replace("$output_dir/", "")
        .replace("${output_dir}/", "");
    if let Some(s) = subject {
        n = n.replace("${subj}", s).replace("$subj", s);
    }
    if n.contains("${run}") || n.contains("$run") {
        return runs
            .iter()
            .map(|r| n.replace("${run}", r).replace("$run", r))
            .collect();
    }
    vec![n]
}

/// Drop names that are not stable outputs: temporaries (`rm.*`), `-`, `.` and
/// other names with no letter or digit, globs,
/// unexpanded variables, absolute or parent-relative paths.
fn keep(name: &str) -> bool {
    !(name.is_empty()
        || !name.chars().any(char::is_alphanumeric)
        || name == "-"
        || name.starts_with("rm.")
        || name.starts_with("./rm.")
        || name.starts_with('/')
        || name.starts_with("..")
        || name.contains(['*', '$', '`', '|', '<', '>']))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture(case: &str) -> String {
        let p = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/processing")
            .join(case)
            .join("proc.sub-01");
        std::fs::read_to_string(p).unwrap()
    }

    fn blocks(s: &ParsedScript) -> Vec<&str> {
        s.steps.iter().map(|b| b.block.as_str()).collect()
    }

    fn step<'a>(s: &'a ParsedScript, block: &str) -> &'a ParsedStep {
        s.steps.iter().find(|b| b.block == block).unwrap()
    }

    fn names(step: &ParsedStep) -> Vec<&str> {
        step.outputs.iter().map(|o| o.name.as_str()).collect()
    }

    #[test]
    fn complete_script_recovers_the_executed_order() {
        let s = parse(&fixture("complete")).unwrap();
        assert_eq!(
            blocks(&s),
            [
                "tcat", "outcount", "tshift", "align", "tlrc", "volreg", "blur", "mask", "scale",
                "regress"
            ]
        );
        assert_eq!(s.subject.as_deref(), Some("sub-01"));
        assert_eq!(s.output_dir.as_deref(), Some("sub-01.results"));
        assert_eq!(s.runs, ["01"]);
        assert!(step(&s, "tcat").auto && !step(&s, "tshift").auto);
    }

    #[test]
    fn non_data_banners_are_not_steps() {
        let s = parse(&fixture("complete")).unwrap();
        for ignored in ["setup", "finalize", "QC_review", "blur estimation"] {
            assert!(!blocks(&s).contains(&ignored), "{ignored}");
        }
    }

    #[test]
    fn omitted_blocks_are_simply_absent() {
        let s = parse(&fixture("omitted")).unwrap();
        assert_eq!(
            blocks(&s),
            ["tcat", "outcount", "tshift", "volreg", "regress"]
        );
    }

    #[test]
    fn custom_order_is_kept_as_executed() {
        let s = parse(&fixture("custom_order")).unwrap();
        assert_eq!(
            blocks(&s),
            ["tcat", "outcount", "tshift", "blur", "volreg", "regress"]
        );
    }

    #[test]
    fn two_runs_expand_run_variables() {
        let s = parse(&fixture("two_runs")).unwrap();
        assert_eq!(s.runs, ["01", "02"]);
        let n = names(step(&s, "tshift"));
        assert!(n.contains(&"pb01.sub-01.r01.tshift"), "{n:?}");
        assert!(n.contains(&"pb01.sub-01.r02.tshift"), "{n:?}");
    }

    #[test]
    fn outputs_come_from_prefix_options_copies_and_redirects() {
        let s = parse(&fixture("complete")).unwrap();
        assert_eq!(names(step(&s, "tcat"))[0], "pb00.sub-01.r01.tcat");
        let volreg = names(step(&s, "volreg"));
        for want in [
            "pb02.sub-01.r01.volreg",
            "anat_final.sub-01",
            "mask_epi_extents",
            "out.allcostX.txt",
            "dfile_rall.1D",
        ] {
            assert!(volreg.contains(&want), "{want} in {volreg:?}");
        }
        let regress = names(step(&s, "regress"));
        for want in [
            "stats.sub-01",
            "errts.sub-01",
            "X.xmat.1D",
            "motion_demean.1D",
        ] {
            assert!(regress.contains(&want), "{want} in {regress:?}");
        }
        let mask = names(step(&s, "mask"));
        assert!(mask.contains(&"out.mask_ae_dice.txt"), "{mask:?}");
        assert!(mask.contains(&"full_mask.sub-01"), "{mask:?}");
    }

    #[test]
    fn temporaries_and_non_outputs_are_dropped() {
        let s = parse(&fixture("complete")).unwrap();
        for st in &s.steps {
            for o in &st.outputs {
                assert!(!o.name.starts_with("rm."), "{}", o.name);
                assert!(!o.name.contains('$'), "{}", o.name);
                assert!(!o.name.contains('*'), "{}", o.name);
            }
        }
    }

    #[test]
    fn outputs_know_their_script_line_and_kind() {
        let text = fixture("complete");
        let s = parse(&text).unwrap();
        let o = step(&s, "tshift")
            .outputs
            .iter()
            .find(|o| o.name == "pb01.sub-01.r01.tshift")
            .unwrap();
        assert_eq!(o.kind, OutputKind::Dataset);
        assert!(text.lines().nth(o.line - 1).unwrap().contains("3dTshift"));
        let log = step(&s, "mask")
            .outputs
            .iter()
            .find(|o| o.name == "out.mask_ae_dice.txt")
            .unwrap();
        assert_eq!(log.kind, OutputKind::File);
    }

    #[test]
    fn align_epi_anat_outputs_come_from_anat_and_suffix() {
        let s = parse(&fixture("complete")).unwrap();
        let n = names(step(&s, "align"));
        assert_eq!(n, ["anat_al_junk", "anat_al_junk_mat.aff12.1D", "anat_ns"]);
        let line = "align_epi_anat.py -anat2epi -anat my.anat+orig.HEAD -epi e+orig";
        let out = outputs_of(line);
        let names: Vec<_> = out.iter().map(|(n, _)| n.as_str()).collect();
        assert_eq!(names, ["my.anat_al", "my.anat_al_mat.aff12.1D"]); // default suffix, no skullstrip
    }

    #[test]
    fn the_generating_command_is_recovered() {
        let s = parse(&fixture("complete")).unwrap();
        let c = s.command.unwrap();
        assert!(c.starts_with("afni_proc.py -subj_id sub-01"), "{c}");
        assert!(c.contains("-dsets epi.r01+orig.HEAD"), "{c}");
        assert!(c.contains("-regress_censor_motion 0.3"), "{c}");
    }

    #[test]
    fn repeated_and_custom_blocks_are_preserved() {
        let text = "#!/bin/tcsh -xef\n\necho \"auto-generated by afni_proc.py, today\"\n\
            set subj = s1\n\
            # ================================ blur =================================\n\
            3dmerge -prefix pb02.$subj.r$run.blur in\n\
            # ================================ mything ==============================\n\
            3dcalc -prefix special.$subj x\n\
            # ================================ blur =================================\n\
            3dmerge -prefix pb03.$subj.r$run.blur in\n";
        let s = parse(text).unwrap();
        assert_eq!(blocks(&s), ["blur", "mything", "blur"]);
        assert_eq!(names(&s.steps[0]), ["pb02.s1.r01.blur"]);
        assert_eq!(names(&s.steps[1]), ["special.s1"]);
        assert_eq!(names(&s.steps[2]), ["pb03.s1.r01.blur"]);
    }

    #[test]
    fn a_script_that_is_not_from_afni_proc_is_rejected() {
        assert_eq!(
            parse("#!/bin/tcsh\necho hello\n"),
            Err(ScriptError::NotAfniProc)
        );
        assert_eq!(parse(""), Err(ScriptError::NotAfniProc));
    }

    #[test]
    fn a_truncated_script_gives_what_it_has() {
        let text = fixture("complete");
        let head: String = text.lines().take(100).collect::<Vec<_>>().join("\n");
        let s = parse(&head).unwrap();
        assert_eq!(blocks(&s), ["tcat", "outcount"]);
        let none = parse("#!/bin/tcsh\necho \"auto-generated by afni_proc.py\"\n").unwrap();
        assert!(none.steps.is_empty());
        assert!(!none.notes.is_empty());
    }

    #[test]
    fn tokens_keep_quoted_parts_together() {
        assert_eq!(
            tokens("3dTcat -prefix a 'epi+orig[0..$]'"),
            ["3dTcat", "-prefix", "a", "epi+orig[0..$]"]
        );
    }

    #[test]
    fn names_with_no_letter_or_digit_are_not_outputs() {
        for odd in [".", "./", "..", "-", ";", ",", "", "()", "_"] {
            assert!(!keep(odd), "{odd:?}");
        }
        for fine in ["mask_group", "full_mask.sub-01", "x", "a.b"] {
            assert!(keep(fine), "{fine}");
        }
    }
}
